package strings;
/*QuesNo-07 --> Given a string, we have to find out all subsequences of it.
 *  A String is a subsequence of a given String, that is generated by deleting
 *   some character of a given string without changing its order ? */
public class QuesNo_07_PrintAllSubsequencesOfaString {
	public static void subSequence(String s) {
		for (int i = 0; i < s.length(); i++) {
			System.out.print(s.charAt(i) + " ");
		}
		System.out.println();
		for (int i = 0; i < s.length(); i++) {
			System.out.print(s.charAt(i));
			if((i+1) == s.length()) {
				System.out.print(s.charAt(0));
			} else {
			    System.out.print(s.charAt(i+1));
			}
			    System.out.print(" ");
		}
		System.out.println();
		System.out.println(s);
	}
	public static void main(String[] args) {
		String s = "abcd";
		subSequence(s);
	}

}
